# Generated by Django 4.2.20 on 2025-09-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_initial'),
    ]

    operations = [
    ]
