# Generated by Django 4.2.20 on 2025-09-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_studentfeemanagement_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeemanagement',
            name='discount',
        ),
    ]
