# Generated by Django 4.2.20 on 2025-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_remove_studentfeemanagement_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeemanagement',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
