# Generated by Django 4.2.20 on 2025-09-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('application', '0018_studentfeemanagement_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='studentfeemanagement',
            name='discount',
        ),
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_fee', to='course_overviews.courseoverview')),
            ],
        ),
    ]
