# Generated by Django 4.2.20 on 2025-09-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_remove_batch_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfeemanagement',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CourseFee',
        ),
    ]
