# Generated by Django 4.2.20 on 2025-09-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('application', '0020_batch_fees_studentfeemanagement_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='course_overviews.courseoverview')),
            ],
        ),
    ]
