# Generated by Django 4.2.20 on 2025-10-06 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0021_coursefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfranchise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userfranchise',
            unique_together={('user', 'franchise', 'batch')},
        ),
    ]
