# Generated by Django 4.2.20 on 2025-10-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_userfranchise_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfranchise',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
