# Generated by Django 4.2.20 on 2025-10-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_userfranchise_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchfeemanagement',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='coursefee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='student_fee_management',
        ),
        migrations.RemoveField(
            model_name='installmenttemplate',
            name='batch_fee_management',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='studentfeemanagement',
            name='batch_fee_management',
        ),
        migrations.RemoveField(
            model_name='studentfeemanagement',
            name='user_franchise',
        ),
        migrations.AlterUniqueTogether(
            name='userfranchise',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfranchise',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='userfranchise',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='userfranchise',
            name='user',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BatchFeeManagement',
        ),
        migrations.DeleteModel(
            name='CourseFee',
        ),
        migrations.DeleteModel(
            name='Franchise',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='InstallmentTemplate',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='StudentFeeManagement',
        ),
        migrations.DeleteModel(
            name='UserFranchise',
        ),
    ]
